COMPILER=g++


all: compile run

compile:
	$(COMPILER) main.cpp -o opengl -lGL -lGLU -lglut

run:
	@echo -----------------------------------------
	@echo Usage:
	@echo 
	@echo ./opengl

clean:
	rm  *~
